### PR TITLE
Implemented routes for friend requests

### LINKED ISSUE #142: Create friend request routes
# Background

Right now, we only have routes to add friends (automatically adds user to both friends fields). Instead, we want to create routes that enable friend requesting, which then will call the add friend helper function when the request is accepted.

# Task

 - Create friendRequests field in user model
 - Create routes to send, accept, and reject friend requests
 - Change addFriend to a helper function that is called when a friend request is accepted

### PR DESCRIPTION
**Pull request by aidenszeto**
# Relevant issue

Closes #142

# Summary of change

 - Added `incomingFriendRequests` and `outgoingFriendRequests` fields to user model
 - Refactored friends routes to use requests instead of purely adding friends
 - Updated package-lock to reflect status after fresh dependency install

# Testing/Verification

 - `/sendFriendRequest` does the following
   - friendId is added to user's outgoingFriendRequests
   - userId is added to friend's incomingFriendRequests
   - If the request already exists of the two users are already friends, an error is thrown
- `/cancelFriendRequest` does the following
  - friendId is removed from user's outgoingFriendRequests
  - userId is removed from friend's incomingFriendRequest
- `/acceptFriendRequest` does the following
  - friendId is moved from user's incomingFriendRequests to friends
  - userId is moved from friend's outgoingFriendRequests to friends
- `/rejectFriendRequest` does the following
  - friendId is removed from user's incomingFriendRequests
  - userId is removed from friend's outgoingFriendRequests

### CODE REVIEW

**Review by nishantbalaji — CHANGES_REQUESTED** [review]
May be an error on my part but found the following errors: 

`/sendFriendRequest` can send to the same user because the userId it's sending to is changing:
image
*sending it again and I get*
image

`/acceptFriendRequest` gives me:
image

Similar things are happening with the other routes. Reject friend request is rejecting even if that person never sent a request.

See the Postman workspace to see how I tested the requests.

**Review by syd-tan — CHANGES_REQUESTED** [review]
I got the same error as @nishantbalaji

**Comment by aidenszeto** [comment]
For the requests that use `req.user._id`, you won't have to include `_id` in the body of the request. Instead, when you login and set the bearer token in Authentication, `req.user._id` will automatically be equal to the user logged in.

The issues you brought up do look like they're unrelated to the auth changes, but it might be worth trying another test. I'll take a look and reply to the comment once I figure some more stuff out too.

**Review by nishantbalaji — APPROVED** [review]
All routes work, LGTM!

**Review by syd-tan — APPROVED** [review]
Lgtm! There are a couple niche cases I tested that I just wanted to let you know about, like users can send friend requests to themselves and also if user 1 sends user 2 a friend request, user 2 can still make a friend request to user 1. However, if one of them accepts, the second request won't go through because they are already friends. I think as long as we make sure this doesn't happen through the front end it should be ok though!

**Comment by aidenszeto** [comment]
Just made the changes needed to support the two edge cases you mentioned.

Now, users shouldn't be able to send themselves friend requests and users will not be able to send a friend request if the target user has already sent them one. Going to merge this - thanks for the reviews!

**Pull request merged**
