### PR TITLE
Popularity

### LINKED ISSUE #43: Listing popularity ranking/scoring
We want to find a way to rank listings by popularity. Here's a potential approach:
- Add a "popularity" field in the Listing model of type `int` 
- Increment the popularity score for every page visit (can either create a new route to call on listing page mount or add the counter to the `/byId/:id` route)
- Reset this score at the beginning of every week

We could also consider when the listing was last visited, so adding a "lastVisited" field in the Listing model is an option as well.

### PR DESCRIPTION
**Pull request by teekenzie**
closes #43

### CODE REVIEW

**Comment by teekenzie** [comment]
@43

**Comment by aidenszeto** [comment]
Has this been fully tested? Let's go through the changes and squash the merge conflicts on Thursday

**Comment by teekenzie** [comment]
Wait this hasn't been tested yet

**Comment by aidenszeto** [comment]
Yeah we can just rebase on Thursday and you can keep working on it throughout this week / next seek

**Review by aidenszeto — APPROVED** [review]

**Pull request merged**
